### ISSUE TITLE
Комментарии к коду в main

### ISSUE THREAD

**Issue by chrn-feip** [GoSum215/fefu_backend_2_3#3]
1. Если вы работаете через докер, то в основной ветке у вас должен быть проект, в файле docker-compose.yml которого настроен контейнер для СУБД POstgreSQL. У вас там mysql. Посмотрите внимательнее на команду из документации и доступные опции для параметра with в ней: https://laravel.com/docs/8.x/installation#choosing-your-sail-services
2. Если вы работаете не через докер, то предполагается, что вы устанавливаете компоненты стека вручную и скачиваете проект через  Composer. Тогда в проекте не будет файла docker-compose.yml, и тогда для вас не актуально писать PR на добавление adminer.

**Comment by chrn-feip** [comment]
Так. Я посмотрела историю коммитов в основном репозитории и пришла в ужас. Давайте не так. Я не могу в такой ситуации гарантировать, что вы вернули проект в целостное состояние после серии удалений. Скачайте проект ЗАНОВО и сразу с постгресом. И в таком неизменном виде залейте в новую ветку, которую сделайте мастером. Старый мастер удалите и больше так не делайте. После этого оставьте тут коммент и не закрывайте  issue. Я сама закрою, если сочту, что всё сделано как нужно.

**Comment by GoSum215** [comment]
Здравствуйте
Не знаю, как делать правильно, поэтому выходит немного костыльно
Я постараюсь исправиться
Надеюсь, в этот раз я нигде не накосячил 🙃

**Comment by chrn-feip** [comment]
Приведите в порядок ветку master. Я не могу без этого принять ДЗ. Должен быть всего 1 коммит в истории коммитов ветки. А не 23 как сейчас. Проще всего это сделать, если эту имеющуюся ветку master удалить, скачать базовый проект заново и выложить его заново в гитхаб как master.

**Comment by GoSum215** [comment]
В этом и проблема
Я не знаю, как удалить текущий master
Единственное, что приходит в голову - это снести репозиторий полностью и создать новый с идентичным названием

**Comment by chrn-feip** [comment]
Ну так задайте вопрос или погуглите. 
Локально удалить ветку можно через git branch -D <название ветки> или через гуи того инструмента, в котором вы работаете с гитом. В "шторме" тоже есть гуи для управления ветками.
Далее скачиваете проект и создаёте заново ветку master. Но на гитхаб её пушите через git push -f origin master. Эта команда перетрёт историю коммитов на гитхабе локальной, в которой вы после скачивания должны сделать один коммит.

**Comment by GoSum215** [comment]
У меня получилось убрать всю хрень в коммитах,
Костылями, поэтому сократить удалось лишь до двух

**Comment by chrn-feip** [comment]
Как вы этого добились? Ваша задача была не убирать вручную всё, что в коммитах сделано, а просто скачать проект ЗАНОВО и перетереть им существующий мастер. В чём сложность?

В данный момент в структуре проекта потеряны папки public, resources, storage как минимум. И я понятия не имею, не потеряны ли какие-то файлы внутри тех папок, которые остались в репозитории.  

Вы потом столкнётесь с проблемами с этим кривым проектом. Мы же с вами обсудили несколько раз что нужно сделать. Удалите папку с существующим проектом, предварительно перенесите файлик docker-compose.yml, чтобы не потерять изменения по админеру или что там у вас. Далее запустите команду 
`curl -s "https://laravel.build/fefu_backend_2_3?with=pgsql" | bash`
Сделайте один единственный коммит и пуш в master. Но push сделайте с -f опцией. Она как раз и отвечает за перезаписывание файлов и истории коммитов.

**Comment by chrn-feip** [comment]
Попросите помощи у одногруппников, если совсем никак не понимаете. Некоторые уже сталкивались с необходимостью перезалить мастер свежим скачанным кодом без лишних коммитов.

**Comment by GoSum215** [comment]
Хорошо, спасибо, буду пытаться
 
Все те коммиты мастера я сократил, объединив их в один. Удалось всё схлопнуть до двух.

Поэтому можно немного уточнения?
Опция -f затрёт историю коммитов и будет выглядеть, будто в репозитории и был изначально 1 коммит?

**Comment by chrn-feip** [comment]
Во всём, что вы пишите, я не вижу ключевого момента - вы скачали проект ЗАНОВО и у вас где-то (мб локально) есть корректная структура проекта, нетронутая, вот как скачали, ровно так и закоммитили. Я не знаю, что вы имеет в виду под сокращением коммитов мастера, но в данный момент код в мастере содержит не все папки. Поэтому вам и предложено заново всё сделать. 

-f перетрёт историю и файлы на удалённом репозитории (то есть в гитхабе) при условии, что вы скачали проект в новую папку, в которой нет гита, сделали один единственный коммит и пытаетесь это пушить в ветку master, находящуюся тут, на гитхабе. Пушить с -f. Вот в этом случае вы сможете получить то, что я прошу. Для самопроверки скачайте в новую папку проект с другим названием и сверьте структуру папок и файлов там, в вашем локальном проекте и на гитхабе. Станет понятнее.

**Comment by chrn-feip** [comment]
https://git-scm.com/docs/git-push#Documentation/git-push.txt--f

**Comment by GoSum215** [comment]
Хорошо, спасибо
Это и надо было сделать изначально

**Comment by GoSum215** [comment]
Кажется, это помогло
А я костылями пытался . . . 
Зато учусь работать с консолью 🙃
